/**
 * The site-wide social card, generated by src/app/opengraph-image.tsx from
 * the same CyberFrame as the per-post and per-case-study images.
 *
 * Next does not deep-merge `openGraph`: a page that defines its own
 * `openGraph` block drops the root layout's images entirely, so every page
 * that sets `openGraph` must include `images: [OG_IMAGE]` itself.
 * src/__tests__/metadata.test.ts checks that it does.
 */
export const OG_IMAGE = '/opengraph-image';
