import { FALLBACK_ICON, glyphs } from './icons/sprite';

export interface IconProps {
  /** Icon name, with or without the legacy `fa-` prefix (FA5 alias names are fine). */
  name: string;
  className?: string;
  /** Accessible label; omitted = decorative (aria-hidden). */
  label?: string;
}

/**
 * Inline SVG icon, sized and coloured like text (1em, currentColor) so it
 * drops in wherever a Font Awesome <i> used to sit. Replaces the 102 KB
 * Font Awesome stylesheet + webfonts with only the glyphs the site uses
 * (src/components/icons/sprite.ts, regenerated by scripts/build-icon-sprite.py).
 */
export default function Icon({ name, className = '', label }: IconProps) {
  const key = name.replace(/^fa-/, '');
  const glyph = glyphs[key] ?? glyphs[FALLBACK_ICON];
  return (
    <svg
      viewBox={glyph.viewBox}
      className={`inline-block h-[1em] w-[1em] align-[-0.125em] fill-current ${className}`.trim()}
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      focusable="false"
    >
      <path d={glyph.d} />
    </svg>
  );
}
