#!/usr/bin/env python3
"""Regenerate src/components/icons/sprite.ts from a Font Awesome Free package.

Usage: python3 scripts/build-icon-sprite.py <path-to-extracted-fontawesome-free-package>
(e.g. `npm pack @fortawesome/fontawesome-free@6.4.2 && tar -xzf *.tgz`, then pass ./package).

Collects every icon name the site references (JSX "fas fa-*" classes, `icon: 'fa-*'`
data fields, and *Icon frontmatter in src/content/services), resolves FA5 aliases via
metadata/icon-families.json, and emits only those glyphs as inline SVG path data. Icons are
CC BY 4.0 (Font Awesome Free); the attribution lives in the generated file.
"""
import json, pathlib, re, sys

pkg = pathlib.Path(sys.argv[1])
root = pathlib.Path(__file__).resolve().parent.parent
meta = json.loads((pkg / "metadata" / "icon-families.json").read_text())

# alias -> canonical
canon = {}
for name, info in meta.items():
    canon[name] = name
    for alias in info.get("aliases", {}).get("names", []):
        canon.setdefault(alias, name)

used = set()
for f in list((root / "src/app").rglob("*.tsx")) + list((root / "src/components").rglob("*.tsx")):
    t = f.read_text()
    used |= set(re.findall(r'"(?:fas|fab|far) fa-([a-z0-9-]+)', t))
    used |= set(re.findall(r"icon: '(?:fa-)?([a-z0-9-]+)'", t))
    used |= set(re.findall(r'<Icon name="([a-z0-9-]+)"', t))  # already-migrated <Icon name="..."/>
for f in (root / "src/content/services").glob("*.md"):
    used |= set(re.findall(r"Icon: '?fa-([a-z0-9-]+)", f.read_text()))
used.add("circle-question")  # fallback

sprite, missing = {}, []
for name in sorted(used):
    c = canon.get(name)
    if not c:
        missing.append(name); continue
    info = meta[c]
    styles = [fs["style"] for fs in info["familyStylesByLicense"]["free"]]
    style = "brands" if "brands" in styles else ("solid" if "solid" in styles else styles[0])
    svg = (pkg / "svgs" / style / f"{c}.svg").read_text()
    vb = re.search(r'viewBox="([^"]+)"', svg).group(1)
    d = " ".join(re.findall(r'<path[^>]*\sd="([^"]+)"', svg))
    sprite[name] = {"viewBox": vb, "d": d}

lines = [
    "// GENERATED by scripts/build-icon-sprite.py — do not edit by hand.",
    "// Icons: Font Awesome Free 6.4.2, CC BY 4.0 (https://fontawesome.com/license/free).",
    "// Only the glyphs this site references are included; FA5 alias names resolve to FA6 glyphs.",
    "export interface Glyph { viewBox: string; d: string }",
    "export const glyphs: Record<string, Glyph> = {",
]
for name, g in sprite.items():
    lines.append(f"  '{name}': {{ viewBox: '{g['viewBox']}', d: '{g['d']}' }},")
lines += ["};", "", "export const FALLBACK_ICON = 'circle-question';", ""]
(root / "src/components/icons/sprite.ts").write_text("\n".join(lines))
print(f"wrote {len(sprite)} glyphs; unresolved: {missing}")
