#!/usr/bin/env python3
"""Regenerate src/app/_og/fonts.generated.ts: Latin subsets of the OG fonts as base64.

Usage: python3 scripts/build-og-fonts.py   (needs `pip install fonttools brotli`)

The OG image routes run on the Cloudflare Workers runtime, which has no
filesystem and cannot fetch file:// URLs, so the fonts are embedded. Subsetting
to Basic Latin + Latin-1 + punctuation keeps the module small.
"""
import base64, io, pathlib
from fontTools import subset
from fontTools.ttLib import TTFont

root = pathlib.Path(__file__).resolve().parent.parent / "src" / "app" / "_og"
UNICODES = "U+0020-007E,U+00A0-00FF,U+2010-2027,U+2030-205E,U+20AC,U+2122,U+2190-2199,U+22C3"

def subset_b64(name: str) -> str:
    font = TTFont(root / "fonts" / name)
    opts = subset.Options(); opts.flavor = None; opts.desubroutinize = True; opts.hinting = False
    sub = subset.Subsetter(opts); sub.populate(unicodes=subset.parse_unicodes(UNICODES)); sub.subset(font)
    buf = io.BytesIO(); font.save(buf); return base64.b64encode(buf.getvalue()).decode()

raj, mono = subset_b64("Rajdhani-Bold.ttf"), subset_b64("ShareTechMono-Regular.ttf")
out = root / "fonts.generated.ts"
out.write_text(
    "// GENERATED by scripts/build-og-fonts.py — do not edit by hand.\n"
    "// Latin subsets of Rajdhani Bold and Share Tech Mono (SIL OFL 1.1; full files and licenses in ./fonts).\n"
    f"export const RAJDHANI_BOLD_B64 = '{raj}';\n"
    f"export const SHARE_TECH_MONO_B64 = '{mono}';\n"
)
print(f"wrote {out.name}: rajdhani {len(raj)//1024} KB, mono {len(mono)//1024} KB (base64)")
